import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import groovy.xml.XmlSlurper

plugins {
    id 'com.android.application' apply false
    id 'com.google.gms.google-services' version '4.5.0' apply false
    id 'com.google.firebase.crashlytics' version '3.0.8' apply false
}

subprojects {
    afterEvaluate {
        if (project.path == ':TMessagesProj' && plugins.hasPlugin("com.android.application")) {
            android {
                compileSdk = 37
                buildToolsVersion = "36.0.0"
                ndkVersion = "27.2.12479018"

                lint {
                    checkReleaseBuilds = false
                    disable 'MissingTranslation', 'ExtraTranslation', 'BlockedPrivateApi'
                }

                compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_21
                    targetCompatibility = JavaVersion.VERSION_21

                    coreLibraryDesugaringEnabled = true
                }

                kotlin {
                    compilerOptions {
                        jvmTarget = JvmTarget.JVM_21
                    }
                }

                defaultConfig {
                    minSdk = 27
                    targetSdk = 36
                }

                buildFeatures.buildConfig = true
            }
        }
    }
    plugins.withId('com.android.application') {
        android {
            androidResources {
                ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~:!optional:!licences:!*stmary*:!*eufb*'
            }
        }
    }

    if (project.projectDir.absolutePath.contains('/TMessagesProj_Modules/media/')) {
        project.plugins.withId('com.android.library') {
            project.android {
                if (namespace == null) {
                    def manifestFile = file("${project.projectDir}/src/main/AndroidManifest.xml")
                    if (manifestFile.exists()) {
                        def manifest = new XmlSlurper().parse(manifestFile)
                        def manifestPackage = manifest.@package.text()
                        if (manifestPackage) {
                            namespace manifestPackage
                        }
                    }
                }
            }
        }
    }
}
